// Extracted from lib.js (issue #1355).
//
// lib.js had reached 20,634 lines against the repo's 500-LOC limit
// (docs/CODING_STANDARDS.md, Sonar S104). It contained no mutual recursion, so it was
// split along its own dependency layering. lib.js remains the barrel every caller imports.

export const TO_CAMEL = {
  login_name: "loginName",
  display_name: "displayName",
  user_id: "userId",
  group_id: "groupId",
  role_id: "roleId",
  requirement_type: "requirementType",
  artifact_type: "artifactType",
  artifact_identifier: "artifactIdentifier",
  artifact_url: "artifactUrl",
  artifact_title: "artifactTitle",
  link_type: "linkType",
  relation_type: "relationType",
  target_id: "targetId",
  new_uid: "newUid",
  uid_prefix: "uidPrefix",
  copy_relations: "copyRelations",
  revision_number: "revisionNumber",
  revision_type: "revisionType",
  sync_status: "syncStatus",
  last_synced_at: "lastSyncedAt",
  source_uid: "sourceUid",
  target_uid: "targetUid",
  source_wave: "sourceWave",
  target_wave: "targetWave",
  requirement_uid: "requirementUid",
  extra_body: "extraBody",
  project_identifier: "projectIdentifier",
  blocking_status: "blockingStatus",
  blocked_by: "blockedBy",
  content_hash: "contentHash",
  model_id: "modelId",
  has_embedding: "hasEmbedding",
  is_stale: "isStale",
  model_mismatch: "modelMismatch",
  current_model_id: "currentModelId",
  embedding_model_id: "embeddingModelId",
  embedded_at: "embeddedAt",
  pairs_analyzed: "pairsAnalyzed",
  embedded_count: "embeddedCount",
  similarity_threshold: "similarityThreshold",
  total_unblocked: "totalUnblocked",
  total_blocked: "totalBlocked",
  total_unconstrained: "totalUnconstrained",
  total_requirements: "totalRequirements",
  created_by: "createdBy",
  baseline_id: "baselineId",
  baseline_name: "baselineName",
  other_baseline_id: "otherBaselineId",
  other_baseline_name: "otherBaselineName",
  added_count: "addedCount",
  removed_count: "removedCount",
  modified_count: "modifiedCount",
  requirement_count: "requirementCount",
  requirement_id: "requirementId",
  from_revision: "fromRevision",
  to_revision: "toRevision",
  field_changes: "fieldChanges",
  relation_changes: "relationChanges",
  traceability_link_changes: "traceabilityLinkChanges",
  change_type: "changeType",
  old_value: "oldValue",
  new_value: "newValue",
  relation_id: "relationId",
  link_id: "linkId",
  metric_type: "metricType",
  metric_param: "metricParam",
  scope_status: "scopeStatus",
  total_gates: "totalGates",
  passed_count: "passedCount",
  failed_count: "failedCount",
  gate_id: "gateId",
  gate_name: "gateName",
  actual_value: "actualValue",
  created_by: "createdBy",
  document_id: "documentId",
  parent_id: "parentId",
  sort_order: "sortOrder",
  section_id: "sectionId",
  content_type: "contentType",
  text_content: "textContent",
  entity_type: "entityType",
  entity_types: "entityTypes",
  edge_type: "edgeType",
  domain_id: "domainId",
  graph_node_id: "graphNodeId",
  requirement_uid: "requirementUid",
  decision_date: "decisionDate",
  superseded_by: "supersededBy",
  asset_type: "assetType",
  asset_id: "assetId",
  asset_uid: "assetUid",
  archived_at: "archivedAt",
  business_context: "businessContext",
  scope_designation: "scopeDesignation",
  // GC-M018: knowledge / completeness dimension on operational asset and
  // asset relation. snake_case wire form maps to the backend's camelCase
  // DTO field; recursive camelization would mangle a user-defined inner
  // metadata key like {"knowledge_state": ...}, so the explicit entry pins
  // the mapping at the boundary (same rationale as GC-M011 clear_subtype).
  knowledge_state: "knowledgeState",
  clear_owner: "clearOwner",
  clear_steward: "clearSteward",
  clear_environment: "clearEnvironment",
  clear_criticality: "clearCriticality",
  clear_business_context: "clearBusinessContext",
  clear_scope_designation: "clearScopeDesignation",
  // GC-M011 — asset subtype + metadata + subtype-schema registry. Without
  // these the snake_case clear flags would not bind on the backend DTO and
  // recursive camelization would mutate user-defined metadata / schema keys
  // (codex pre-push review #722).
  clear_subtype: "clearSubtype",
  clear_metadata: "clearMetadata",
  schema_version: "schemaVersion",
  schema_body: "schemaBody",
  schema_description: "description",
  clear_schema_description: "clearDescription",
  clear_schema_body: "clearSchemaBody",
  member_uids: "memberUids",
  root_uids: "rootUids",
  target_type: "targetType",
  target_entity_id: "targetEntityId",
  target_identifier: "targetIdentifier",
  target_url: "targetUrl",
  target_title: "targetTitle",
  source_system: "sourceSystem",
  source_id: "sourceId",
  collected_at: "collectedAt",
  external_source_id: "externalSourceId",
  external_id_id: "externalIdId",
  observation_key: "observationKey",
  observation_value: "observationValue",
  observed_at: "observedAt",
  expires_at: "expiresAt",
  verified_at: "verifiedAt",
  assurance_level: "assuranceLevel",
  evidence_ref: "evidenceRef",
  observation_id: "observationId",
  fair_sentence: "fairSentence",
  // Backend ThreatModelRequest fields. RiskScenario renamed its analogous fields
  // (threat_source→threat, threat_event→method) per GC-T013 / #720, but
  // ThreatModel still uses `threatSource` / `threatEvent` on the wire and the
  // MCP `gc_threat_model` surface still accepts `threat_source` / `threat_event`
  // — without these mappings Jackson silently drops the fields and the create
  // body lands without the threat source / event (issue #875).
  threat_source: "threatSource",
  threat_event: "threatEvent",
  // Backend ThreatModelRequest uses `stride` (typed StrideCategory) on the wire;
  // the MCP surface keeps `stride_category` for clarity. Mapping is needed to
  // bridge the rename; without it Jackson silently dropped the field (issue #875).
  stride_category: "stride",
  clear_stride: "clearStride",
  clear_narrative: "clearNarrative",
  // TC-001 / ADR-040 — TestCaseRequest fields and the partial-update clear
  // flags. Missing entries here cause `gc_test_case` to forward the snake
  // names to Spring, which Jackson silently drops (the codex cycle-1 finding).
  estimated_duration_seconds: "estimatedDurationSeconds",
  clear_description: "clearDescription",
  clear_preconditions: "clearPreconditions",
  clear_postconditions: "clearPostconditions",
  clear_estimated_duration: "clearEstimatedDuration",
  // TC-002 / ADR-041 — TestCaseStepRequest / UpdateTestCaseStepRequest fields.
  // Same rationale as the TC-001 entries above: omitting these would let
  // `gc_test_case` step actions forward snake-case names that Jackson drops.
  step_number: "stepNumber",
  expected_result: "expectedResult",
  actual_result: "actualResult",
  clear_actual_result: "clearActualResult",
  // TC-004 / ADR-042 — TestCaseGherkinRequest field. `gherkin_source` is the
  // MCP arg name (chosen to namespace away from other "source" args on
  // gc_test_case); it maps to the backend's `source` body field via the
  // step-style explicit body construction in index.js, not via this table.
  // The `format` MCP arg is already snake-free, so no entry needed here.
  // TC-005 / ADR-043 — TestCaseFolderRequest / move / copy / reorder fields.
  // Same rationale: missing entries here would let `gc_test_case` forward
  // snake-case names that Jackson silently drops on the backend.
  parent_folder_id: "parentFolderId",
  sort_order: "sortOrder",
  folder_title: "title",
  folder_description: "description",
  clear_folder_description: "clearDescription",
  new_uid: "newUid",
  ordered_folder_ids: "orderedFolderIds",
  ordered_test_case_ids: "orderedTestCaseIds",
  // TC-006 / ADR-044 — TestPlanRequest / UpdateTestPlanRequest fields.
  // Same rationale as the TC-001 entries above: omitting these would let
  // `gc_test_plan` forward snake-case names that Jackson drops on the
  // backend DTO.
  start_date: "startDate",
  end_date: "endDate",
  clear_product: "clearProduct",
  clear_version: "clearVersion",
  clear_build: "clearBuild",
  clear_start_date: "clearStartDate",
  clear_end_date: "clearEndDate",
  // TC-007 / ADR-047 — TestSuite / TestSuiteMember / TestSuiteSourceRequirement
  // fields. The `gc_test_suite` consolidated tool accepts snake_case args and
  // forwards them to camelCase backend DTOs; omitting any mapping below would
  // silently drop the field on the way through Jackson.
  population_mode: "populationMode",
  test_case_id: "testCaseId",
  test_suite_id: "testSuiteId",
  test_case_uid: "testCaseUid",
  criteria_status: "criteriaStatus",
  criteria_type: "criteriaType",
  criteria_priority: "criteriaPriority",
  criteria_format: "criteriaFormat",
  criteria_folder_id: "criteriaFolderId",
  criteria_text_search: "criteriaTextSearch",
  clear_criteria_status: "clearCriteriaStatus",
  clear_criteria_type: "clearCriteriaType",
  clear_criteria_priority: "clearCriteriaPriority",
  clear_criteria_format: "clearCriteriaFormat",
  clear_criteria_folder_id: "clearCriteriaFolderId",
  clear_criteria_text_search: "clearCriteriaTextSearch",
  // TC-008 / ADR-049 — TestRun / TestRunTesterAssignment / TestRunCaseResult
  // fields. The `gc_test_run` consolidated tool accepts snake_case args and
  // forwards them to camelCase backend DTOs; omitting any mapping below would
  // silently drop the field on the way through Jackson.
  // The asset-side `clear_environment` mapping above also covers TestRun's
  // identical clear flag (same key, same camelCase target). The result-row
  // `status` field is constructed explicitly in index.js's update_result
  // handler so it bypasses the snake→camel pass without needing a `result_status`
  // entry here.
  test_plan_id: "testPlanId",
  test_run_id: "testRunId",
  test_case_title: "testCaseTitle",
  start_at: "startAt",
  end_at: "endAt",
  tester_name: "testerName",
  clear_start_at: "clearStartAt",
  clear_end_at: "clearEndAt",
  clear_notes: "clearNotes",
  // TC-009 / ADR-050 (test-execution step-result) — step-result + cursor fields.
  // The step-level `status` field is constructed explicitly in index.js's
  // update_step_result handler so the MCP-side `step_status` argument
  // (disambiguated from the run-level `status` like `result_status`) doesn't
  // bleed through the snake→camel pass.
  case_result_id: "caseResultId",
  step_result_id: "stepResultId",
  current_case_result_id: "currentCaseResultId",
  current_step_result_id: "currentStepResultId",
  executed_at: "executedAt",
  clear_comment: "clearComment",
  clear_executed_at: "clearExecutedAt",
  clear_cursor: "clearCursor",
  // Snapshot fields on TestRunStepResultResponse so the toSnakeCase pass on
  // the read shape gives MCP callers consistently snake-cased names for
  // every field the runner UI displays.
  test_run_case_result_id: "testRunCaseResultId",
  test_case_step_id: "testCaseStepId",
  step_number_snapshot: "stepNumberSnapshot",
  action_snapshot: "actionSnapshot",
  expected_result_snapshot: "expectedResultSnapshot",
  snapshot_order: "snapshotOrder",
  // GC-V001 finding adapter — backend FindingRequest / UpdateFindingRequest
  // use these camelCase field names. Mapping is needed so `gc_finding` reaches
  // backend Bean Validation with the right field names (issue #279).
  finding_id: "findingId",
  finding_type: "findingType",
  root_cause_analysis: "rootCauseAnalysis",
  clear_root_cause_analysis: "clearRootCauseAnalysis",
  clear_owner: "clearOwner",
  clear_due_date: "clearDueDate",
  time_horizon: "timeHorizon",
  observation_refs: "observationRefs",
  topology_context: "topologyContext",
  risk_scenario_id: "riskScenarioId",
  threat_model_id: "threatModelId",
  risk_register_record_id: "riskRegisterRecordId",
  methodology_profile_id: "methodologyProfileId",
  methodology_strategy_key: "methodologyStrategyKey",
  profile_key: "profileKey",
  input_schema: "inputSchema",
  output_schema: "outputSchema",
  crosswalk_entries: "crosswalkEntries",
  // risk_appetite_profile fields (GC-T005)
  appetite_key: "appetiteKey",
  methodology_family: "methodologyFamily",
  appetite_statement: "appetiteStatement",
  tolerance_thresholds: "toleranceThresholds",
  effective_from: "effectiveFrom",
  effective_to: "effectiveTo",
  review_cadence: "reviewCadence",
  next_review_at: "nextReviewAt",
  category_tags: "categoryTags",
  decision_metadata: "decisionMetadata",
  asset_scope_summary: "assetScopeSummary",
  risk_scenario_ids: "riskScenarioIds",
  control_function: "controlFunction",
  control_id: "controlId",
  control_uid: "controlUid",
  // ControlTest fields (ADR-038)
  test_steps: "testSteps",
  expected_results: "expectedResults",
  actual_results: "actualResults",
  tester_identity: "testerIdentity",
  test_date: "testDate",
  implementation_scope: "implementationScope",
  methodology_factors: "methodologyFactors",
  methodology_influence: "methodologyInfluence",
  analyst_identity: "analystIdentity",
  input_factors: "inputFactors",
  observation_date: "observationDate",
  assessment_at: "assessmentAt",
  uncertainty_metadata: "uncertaintyMetadata",
  computed_outputs: "computedOutputs",
  evidence_refs: "evidenceRefs",
  observation_ids: "observationIds",
  approval_state: "approvalState",
  due_date: "dueDate",
  action_items: "actionItems",
  reassessment_triggers: "reassessmentTriggers",
  reassessment_required_at: "reassessmentRequiredAt",
  root_node_ids: "rootNodeIds",
  max_depth: "maxDepth",
  source_node_id: "sourceNodeId",
  target_node_id: "targetNodeId",
  pack_id: "packId",
  pack_type: "packType",
  version_constraint: "versionConstraint",
  source_url: "sourceUrl",
  signature_info: "signatureInfo",
  registry_metadata: "registryMetadata",
  default_outcome: "defaultOutcome",
  performed_by: "performedBy",
  catalog_status: "catalogStatus",
  trust_outcome: "trustOutcome",
  trust_reason: "trustReason",
  install_outcome: "installOutcome",
  error_detail: "errorDetail",
  installed_entity_id: "installedEntityId",
  performed_at: "performedAt",
  resolved_version: "resolvedVersion",
  resolved_source: "resolvedSource",
  resolved_checksum: "resolvedChecksum",
  requested_version: "requestedVersion",
  signature_verified: "signatureVerified",
  signer_trusted: "signerTrusted",
  trust_policy_id: "trustPolicyId",
  registered_at: "registeredAt",
  implementation_guidance: "implementationGuidance",
  expected_evidence: "expectedEvidence",
  framework_mappings: "frameworkMappings",
  pack_metadata: "packMetadata",
  control_pack_entries: "controlPackEntries",
  // Analysis sweep + status-drift response fields
  has_problems: "hasProblems",
  total_problems: "totalProblems",
  status_drift: "statusDrift",
  draft_requirements_scanned: "draftRequirementsScanned",
  minimum_confidence: "minimumConfidence",
  strongest_signal: "strongestSignal",
  // #1106 — methodology profile treatment strategy vocabulary. The camelCase
  // form is already in OPAQUE_VALUE_KEYS; the snake_case form needs an explicit
  // entry here so toCamelCase sees it and OPAQUE_VALUE_KEYS guards both forms.
  treatment_strategy_vocabulary: "treatmentStrategyVocabulary",
  // #1106 — verification result. evidence is a Map<String,Object> (opaque).
  // OPAQUE_VALUE_KEYS already has no entry for it — add both forms.
  // Shared active MCP response/request fields.
  requirement_uids: "requirementUids",
  issue_number: "issueNumber",
  pr_number: "prNumber",
  started_at: "startedAt",
  cycle_index: "cycleIndex",
  duration_ms: "durationMs",
  // Durable station-observation attempts use explicit outcomes; these are issue-thread
  // recovery facts, not a backend measurement projection.
  station_id: "stationId",
  station_result: "stationResult",
  // GC-O009 #1278 — Workflow control surface (start/status/signal). snake_case MCP
  // args / response fields → camelCase backend DTO fields (StartWorkflowExecutionRequest,
  // SendSignalRequest, WorkflowExecutionResponse). Missing entries would drop request
  // fields on write and emit camelCase on reads.
  workflow_id: "workflowId",
  run_id: "runId",
  signal_type: "signalType",
  retry_from_phase: "retryFromPhase",
  completion_command: "completionCommand",
  sonar_project_key: "sonarProjectKey",
  review_cap: "reviewCap",
  poll_interval_seconds: "pollIntervalSeconds",
  start_time: "startTime",
  close_time: "closeTime",
  history_length: "historyLength",
  // GC-U001 / ADR-047 — Audit entity. snake_case MCP args → camelCase backend
  // DTO fields. Missing entries would cause Jackson to silently drop the fields.
  audit_id: "auditId",
  audit_type: "auditType",
  audit_uid: "auditUid",
  scope_description: "scopeDescription",
  team_members: "teamMembers",
  planned_start: "plannedStart",
  planned_end: "plannedEnd",
  actual_start: "actualStart",
  actual_end: "actualEnd",
  phase_kind: "kind",
  clear_objectives: "clearObjectives",
  clear_phases: "clearPhases",
  clear_team_members: "clearTeamMembers",
  // GC-GRC-005 — architecture-model aggregate.
  model_version: "modelVersion",
  commit_sha: "commitSha",
  stable_key: "stableKey",
  element_kind: "elementKind",
  source_path: "sourcePath",
  trust_boundary_key: "trustBoundaryKey",
  data_classification_key: "dataClassificationKey",
  flow_source_stable_key: "flowSourceStableKey",
  flow_target_stable_key: "flowTargetStableKey",
  flow_direction: "flowDirection",
  provenance_source: "provenanceSource",
  provenance_key: "provenanceKey",
  adapter_id: "adapterId",
  tool_name: "toolName",
  tool_version: "toolVersion",
  ruleset_name: "rulesetName",
  ruleset_version: "rulesetVersion",
  derivation_run_id: "derivationRunId",
  from_snapshot_id: "fromSnapshotId",
  to_snapshot_id: "toSnapshotId",
  // GC-GRC-016 — on-demand assessment lane.
  base_commit_sha: "baseCommitSha",
  declared_boundaries: "declaredBoundaries",
  path_selectors: "pathSelectors",
  scope_type: "scopeType",
  scope_values: "scopeValues",
  threat_pack_id: "threatPackId",
  threat_pack_version: "threatPackVersion",
  review_policy: "reviewPolicy",
  review_decision: "reviewDecision",
  reviewed_by: "reviewedBy",
  review_rationale: "reviewRationale",
  idempotency_key: "idempotencyKey",
  partition_limit: "partitionLimit",
};
