// `grndctl init` (issue #1587): set up Ground Control for the one repository it runs in.
//
// Detection proposes; the operator decides. Every value is shown with its evidence and confirmed
// or edited, the full set of file changes is previewed, and nothing is written until the operator
// confirms that preview. A non-interactive run never accepts a detected value: it requires every
// field as an explicit flag. Only this repository's own files are touched, and an existing
// `.ground-control.yaml` or `.env` is never rewritten.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { dump as dumpYaml } from "js-yaml";
import { parseGroundControlYaml } from "./ground-control-config.js";
import { detectRepoFacts } from "./grndctl-detect.js";
import { execFile } from "./runtime-primitives.js";

// The installed package carries the template under templates/; a repository checkout has it at the
// repository root, which is where the pack step copies it from.
const ENV_TEMPLATE_CANDIDATES = [
  fileURLToPath(new URL("../templates/env.example", import.meta.url)),
  fileURLToPath(new URL("../../../.env.example", import.meta.url)),
];

export function resolveEnvTemplatePath() {
  const path = ENV_TEMPLATE_CANDIDATES.find((candidate) => existsSync(candidate));
  if (!path) throw new Error("grndctl is missing its .env template; reinstall the package");
  return path;
}
export const MCP_SERVER_ENTRY = Object.freeze({ type: "stdio", command: "grndctl", args: ["mcp"] });

/** The confirmable fields, in prompt order. `flag` is the non-interactive spelling. */
export const INIT_FIELDS = Object.freeze([
  { key: "project", flag: "--project", label: "Project id (lowercase letters, digits, hyphens)", required: true },
  { key: "github_repo", flag: "--github-repo", label: "GitHub repository (owner/name)", required: true },
  { key: "base_branch", flag: "--base-branch", label: "Base branch PRs target" },
  { key: "test_command", flag: "--test-command", label: "Test command" },
  { key: "completion_command", flag: "--completion-command", label: "Completion gate command" },
  { key: "lint_command", flag: "--lint-command", label: "Lint command" },
  { key: "format_command", flag: "--format-command", label: "Format command" },
  { key: "sonar_project_key", flag: "--sonar-project-key", label: "SonarCloud project key" },
  { key: "sonar_organization", flag: "--sonar-organization", label: "SonarCloud organization" },
  { key: "adr_dir", flag: "--adr-dir", label: "ADR directory" },
  { key: "plan_rules", flag: "--plan-rules", label: "Create an empty .gc/plan-rules.md for repo-specific plan rules? (yes/no)", yesNo: true },
]);

/** Build `.ground-control.yaml` text from confirmed values, validated by the server's own parser. */
export function buildGroundControlYaml(values) {
  const config = { schema_version: 1, project: values.project, github_repo: values.github_repo };
  const workflow = {};
  for (const key of ["test_command", "completion_command", "lint_command", "format_command", "base_branch"]) {
    if (values[key]) workflow[key] = values[key];
  }
  if (Object.keys(workflow).length > 0) config.workflow = workflow;
  if (values.sonar_project_key && values.sonar_organization) {
    config.sonarcloud = { project_key: values.sonar_project_key, organization: values.sonar_organization };
  }
  if (values.plan_rules === "yes") config.rules = { plan_rules: ".gc/plan-rules.md" };
  if (values.adr_dir) config.docs = { adr_dir: values.adr_dir };
  const text = `# Ground Control repository context (generated by grndctl init).\n${dumpYaml(config, { lineWidth: -1 })}`;
  const parsed = parseGroundControlYaml(text);
  if (!parsed.ok) throw new Error(`generated .ground-control.yaml is invalid: ${parsed.errors.join("; ")}`);
  return text;
}

function readJson(path) {
  if (!existsSync(path)) return {};
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch (error) {
    throw new Error(`${path} is not valid JSON; fix it before running init: ${error.message}`);
  }
}

async function envIsIgnored(cwd) {
  try {
    await execFile("git", ["-C", cwd, "check-ignore", "-q", ".env"]);
    return true;
  } catch {
    return false;
  }
}

function planYamlChange(cwd, values) {
  const path = join(cwd, ".ground-control.yaml");
  if (existsSync(path)) return { path, action: "keep", note: "already exists; not rewritten (run grndctl doctor to validate it)" };
  return { path, action: "create", content: buildGroundControlYaml(values) };
}

function planMcpChange(cwd) {
  const path = join(cwd, ".mcp.json");
  const mcp = readJson(path);
  const current = mcp.mcpServers?.["ground-control"];
  if (JSON.stringify(current) === JSON.stringify(MCP_SERVER_ENTRY)) {
    return { path, action: "keep", note: "ground-control entry already runs grndctl mcp" };
  }
  const next = { ...mcp, mcpServers: { ...mcp.mcpServers, "ground-control": MCP_SERVER_ENTRY } };
  return {
    path,
    action: existsSync(path) ? "update" : "create",
    content: `${JSON.stringify(next, null, 2)}\n`,
    note: current ? "replaces only the ground-control entry; other servers are kept" : "adds the ground-control entry",
  };
}

async function planEnvChanges(cwd) {
  const changes = [];
  const envPath = join(cwd, ".env");
  if (existsSync(envPath)) {
    changes.push({ path: envPath, action: "keep", note: "already exists; values are never changed" });
  } else {
    changes.push({ path: envPath, action: "create", content: readFileSync(resolveEnvTemplatePath(), "utf8"), note: "commented template; fill in the credentials this repo needs" });
  }
  if (await envIsIgnored(cwd)) return changes;
  const gitignorePath = join(cwd, ".gitignore");
  const existing = existsSync(gitignorePath) ? readFileSync(gitignorePath, "utf8") : "";
  const separator = existing === "" || existing.endsWith("\n") ? "" : "\n";
  changes.push({ path: gitignorePath, action: existing ? "update" : "create", content: `${existing}${separator}.env\n`, note: "ignores .env, which holds this repository's credentials" });
  return changes;
}

/** Every change init would make, as `{ path, action, content?, note }`, without writing anything. */
export async function planInit(cwd, values) {
  const changes = [planYamlChange(cwd, values), planMcpChange(cwd), ...(await planEnvChanges(cwd))];
  const planRulesPath = join(cwd, ".gc", "plan-rules.md");
  if (values.plan_rules === "yes" && !existsSync(planRulesPath)) {
    changes.push({ path: planRulesPath, action: "create", content: "# Plan rules\n\nRepository-specific constraints every /implement plan must satisfy. One bullet per rule.\n" });
  }
  return changes;
}

export function applyInit(changes) {
  for (const change of changes) {
    if (change.content === undefined) continue;
    mkdirSync(dirname(change.path), { recursive: true });
    writeFileSync(change.path, change.content);
  }
}

function flagValue(args, flag) {
  const inline = args.find((arg) => arg.startsWith(`${flag}=`));
  if (inline !== undefined) return inline.slice(flag.length + 1);
  const i = args.indexOf(flag);
  return i >= 0 && i + 1 < args.length ? args[i + 1] : undefined;
}

/** Values for a non-interactive run: every field must be given explicitly; nothing is detected. */
export function valuesFromFlags(args) {
  const values = {};
  const missing = [];
  for (const field of INIT_FIELDS) {
    const value = flagValue(args, field.flag);
    if (value === undefined) missing.push(field.flag);
    else values[field.key] = value.trim();
  }
  return { values, missing };
}

export function validateValues(values) {
  const errors = [];
  for (const field of INIT_FIELDS) {
    if (field.required && !values[field.key]) errors.push(`${field.flag} is required`);
    if (field.yesNo && !["yes", "no"].includes(values[field.key])) errors.push(`${field.flag} must be yes or no`);
  }
  if (Boolean(values.sonar_project_key) !== Boolean(values.sonar_organization)) {
    errors.push("--sonar-project-key and --sonar-organization must be set together");
  }
  return errors;
}

function proposalFor(field, facts) {
  if (field.yesNo) return { value: "no", source: "default" };
  return facts[field.key] ?? { value: null, source: null };
}

function promptHint(field, proposal) {
  if (proposal.value) return ` [${proposal.value}] (${proposal.source})`;
  return field.required ? " (required)" : " (blank to omit)";
}

/** The problem with an answer to `field`, or null when it is acceptable. */
function answerProblem(field, value) {
  if (field.required && !value) return `  ${field.label} is required.`;
  if (field.yesNo && !["yes", "no"].includes(value)) return "  Answer yes or no.";
  return null;
}

/** Ask for every field, offering the detected value and its evidence as the default. */
export async function confirmValues(ask, facts, print) {
  const values = {};
  for (const field of INIT_FIELDS) {
    const proposal = proposalFor(field, facts);
    const hint = promptHint(field, proposal);
    let value = null;
    while (value === null) {
      const answer = (await ask(`${field.label}${hint}: `)).trim();
      const candidate = answer === "" ? proposal.value ?? "" : answer;
      const problem = answerProblem(field, candidate);
      if (problem) print(problem);
      else value = candidate;
    }
    values[field.key] = value;
  }
  return values;
}

export function renderPlan(changes) {
  const lines = ["", "grndctl init will make these changes:"];
  for (const change of changes) {
    const note = change.note ? ` - ${change.note}` : "";
    lines.push(`  ${change.action.padEnd(6)} ${change.path}${note}`);
    if (change.content !== undefined && !change.path.endsWith(".env")) {
      lines.push(...change.content.trimEnd().split("\n").map((line) => `         | ${line}`));
    }
  }
  return lines.join("\n");
}

export async function runInit(args, { cwd = process.cwd(), ask, print = console.log, interactive }) {
  const nonInteractive = args.includes("--non-interactive");
  if (!nonInteractive && !interactive) {
    print("grndctl init confirms every value, so it needs a terminal. For scripts, pass every value as a flag with --non-interactive.");
    return 2;
  }
  let values;
  if (nonInteractive) {
    const fromFlags = valuesFromFlags(args);
    if (fromFlags.missing.length > 0) {
      print(`--non-interactive needs every value as a flag; missing: ${fromFlags.missing.join(", ")}`);
      return 2;
    }
    values = fromFlags.values;
  } else {
    values = await confirmValues(ask, await detectRepoFacts(cwd), print);
  }
  const errors = validateValues(values);
  if (errors.length > 0) {
    print(errors.join("\n"));
    return 2;
  }
  const changes = await planInit(cwd, values);
  print(renderPlan(changes));
  if (args.includes("--dry-run")) return 0;
  if (!nonInteractive) {
    const confirm = (await ask("\nWrite these changes? [y/N]: ")).trim().toLowerCase();
    if (confirm !== "y" && confirm !== "yes") {
      print("No changes written.");
      return 1;
    }
  }
  applyInit(changes);
  print("Done. Restart your agent session so it starts `grndctl mcp` for this repository.");
  return 0;
}
